# Generated by Django 4.2.1 on 2023-05-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_created_date_product_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-created_date',), 'verbose_name': 'پروژه', 'verbose_name_plural': 'پروژه ها'},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ('-created_date',), 'verbose_name': 'کارگر', 'verbose_name_plural': 'کارگران'},
        ),
    ]
