# Generated by Django 4.2.1 on 2023-06-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_project_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'وضعیت ابزار',
                'verbose_name_plural': 'وضعیت ابزارآلات',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.toolsstatus')),
            ],
            options={
                'verbose_name': 'ابزار',
                'verbose_name_plural': 'ابزارآلات',
                'ordering': ('name',),
            },
        ),
    ]
