# Generated by Django 4.2.1 on 2023-06-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_toolsstatus_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='worker/default.png', upload_to='worker/'),
        ),
    ]
