# Generated by Django 4.2.1 on 2023-06-01 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_worker_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
