# Generated by Django 4.2.1 on 2023-06-01 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_project_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='image',
            field=models.ImageField(default='tools/machine.png', upload_to='tools/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='completion',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
