# Generated by Django 4.2.1 on 2023-06-01 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_tools_image_alter_product_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tools',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
