# Generated by Django 4.2.1 on 2023-06-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='card_number',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
